"""Add delivery_confirmed field to orders

Revision ID: 19420fa100b7
Revises: 189533961e20
Create Date: 2025-12-06 17:10:03.275191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19420fa100b7'
down_revision = '189533961e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_confirmations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_proof', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivery_confirmed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('issues_reported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('issue_description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['delivery_confirmed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issue_description')
        batch_op.drop_column('issues_reported')
        batch_op.drop_column('buyer_feedback')
        batch_op.drop_column('buyer_rating')
        batch_op.drop_column('delivery_confirmed_by')
        batch_op.drop_column('delivery_confirmed_at')
        batch_op.drop_column('delivery_notes')
        batch_op.drop_column('delivery_proof')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('delivery_confirmed')

    op.create_table('delivery_confirmations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_signature', sa.VARCHAR(length=500), nullable=True),
    sa.Column('items_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('condition_good', sa.BOOLEAN(), nullable=True),
    sa.Column('received_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('buyer_notes', sa.TEXT(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('delivery_person_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
